version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_finance_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: finance_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: user_password_here
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # (Opcional) Gestor de base de datos visual en el navegador
  adminer:
    image: adminer
    container_name: adminer_finance
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data: